---
title: "anonymous function"
author: "GLSI"
date: "April 4, 2019"
output: html_document
---

```{r page source}

library(tidyverse)
library("httr")

get_http <- GET("https://data.iowa.gov/resource/s3p7-wy6w.json") 
## Make a request. status_code: To note it, Status: 200, means successful request. Status: 404, as you know very well, means server not found. 

library(httr)
page_source <- function(department, fiscal_year){
  url <- sprintf("https://data.iowa.gov/resource/s3p7-wy6w.json?$limit=100&$offset=0&$order=:id&department=%s&fiscal_year=%f", department, fiscal_year)
  initialjson <- jsonlite::fromJSON(url)
  response <- GET(url)
  if(http_error(response)){
    stop("The request failed")}
  else {
    result <- content(response)
    return(result)
  }
  salary_2018 <- jsonlite::fromJSON(initialjson)
}

json_format <- page_source("Iowa%20State%20University", 2018)
```

```{r dataframe}
# To create dataframe

df_list <- lapply(json_format, function(x) {
  x[sapply(x, is.null)] <- NA
  unlist(x)
})

df <- do.call("rbind", df_list) # Convert list to dataframe
df_Cysalary <- as.data.frame.matrix(df) 
df_Cysalary

#data <- fromJSON("https://data.iowa.gov/resource/s3p7-wy6w.json?$limit=100&$offset=0&$order=:id&department=Iowa%20State%20University&fiscal_year=2018", flatten = TRUE)
#colnames(data)

```


#' Anonymize some information in the dataframe.
#'
#' @param df The name of the file includes a dataframe.
#' @param algo The algorithms to be used. The available choices are md5, which is also the default, sha1, crc32, sha256, sha512, xxhash32, xxhash64, and murmur32.
#' @export
#' @return Returns the dataframe.
#' @examples
#' #Choose the trageted columns to mask.  
#' 

```{r function}
anonymize <- function(df, algo="crc32"){
  library(data.table)
  library(digest)
  library(assertthat)
  
  unq_hashes <- vapply(unique(df), function(object) digest(object, algo=algo), FUN.VALUE="", USE.NAMES=TRUE)
  unname(unq_hashes[df])
  
  assertthat::assert_that(is.string(algo), msg = "The type of algorithm is not string!")
}
```

```{r anonymizing}
cols_to_mask <- c("name", "position")
assertthat::see_if(is.character(cols_to_mask), msg = "The selected columns are not character!")

setDT(df_Cysalary)
assertthat::see_if(is.data.table (df_Cysalary), msg = "The dataframe is not converted to a table!")

df_Cysalary_org <- copy(df_Cysalary)
df_Cysalary <- df_Cysalary[,cols_to_mask := lapply(.SD, anonymize),.SDcols=cols_to_mask,with=FALSE]

head(df_Cysalary, 3)
```





